---
kind: "Service"
apiVersion: "v1"
metadata:
  name: service-discovery
  labels:
    name: service-discovery
    version: 0.0.4
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: external
  selector:
    name: service-discovery
