---
kind: "Service"
apiVersion: "v1"
metadata:
  name: service-discovery
  labels:
    name: service-discovery
    version: 0.0.4
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: service-discovery
