---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: permissions
  labels:
    name: permissions
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      name: "permissions"
  template:
    metadata:
      labels:
        name: "permissions"
        version: "0.0.7"
    spec:
      containers:
        - name: "permissions"
          image: "gcr.io/sd-poc/permissions:0.0.7"
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              memory: 10Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          ports:
            - containerPort: 3000
              name: "external"
              protocol: "TCP"
